In [ ]:
import numpy as np
import pandas as pd

In [ ]:
sr1 = pd.Series([1,2,3,4,5])
sr1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
sr1.iloc[4]

np.int64(5)

In [ ]:
sr1.dtype

dtype('int64')

In [ ]:
sr1.shape

(5,)

In [ ]:
sr1.ndim

1

In [ ]:
sr2 = pd.Series([1,2,3,4,5], index= ['a','b','c','d','e'],name='RollNo')
sr2

a    1
b    2
c    3
d    4
e    5
Name: RollNo, dtype: int64

In [ ]:
sr2.iloc[2]

np.int64(3)

In [ ]:
sr2.loc['c']

np.int64(3)

In [ ]:
sr = pd.Series([1,2.5,3,4,5,'a'])
sr

0      1
1    2.5
2      3
3      4
4      5
5      a
dtype: object

In [ ]:
sr.dtype

dtype('O')

In [ ]:
df1 = pd.DataFrame({'SrNo':[1,2,3,4,5],
                    'Name': ['a','b','c','d','e']})

In [ ]:
df1

   SrNo Name
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e

In [ ]:
df2 = pd.DataFrame({'SrNo':[1,2,3,4,5],
                    'Name': ['a','b','c','d','e']}, index= [1,2,3,4,5])
df2

   SrNo Name
1     1    a
2     2    b
3     3    c
4     4    d
5     5    e

In [ ]:
df2.iloc[0,1]

'a'

In [ ]:
df2.loc[1,'Name']

'a'

In [ ]:
df2.iloc[0:3,]

   SrNo Name
1     1    a
2     2    b
3     3    c

In [ ]:
df2.loc[1:3,'SrNo']

1    1
2    2
3    3
Name: SrNo, dtype: int64

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SrNo    5 non-null      int64
 1   Name    5 non-null      object
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

Data cleaning was taught again using the L1 notebook.